name: Deploy site

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.py'
      - .github/workflows/dco-*.yml
      - .github/workflows/retile.yml
      - .github/workflows/validate.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build site
    runs-on: ubuntu-26.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install jekyll minify ruby-jekyll-redirect-from
      - name: Check out repo
        uses: actions/checkout@v7
      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Build
        run: |
          jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          minify -ri _site --exclude '_site/api/**'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5

  deploy:
    name: Deploy site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
